config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
  end

  get 'movies/index'
  get 'movies/:movieid/like' => 'movies#like', as: :like_movie
  get 'movies/:movieid/hate' => 'movies#hate', as: :hate_movie

   root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :votes
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 2 }
  scope :ordered, ->(field) { order(field || 'created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes
  has_many :movies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Code for Auth, the :name attribute has to be whitelisted
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end



end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, only: [:show, :new, :edit, :create, :update, :destroy, :like, :hate]

  def index
    sort_params = {'by_date' => 'movies.created_at', 'by_title' => 'movies.title', 'by_likes' => 'likes DESC', 'by_hates' => 'hates DESC'}

    filter_params = {'by_user' => 'movies.user_id'}
    whereQuery = ''
    if where_params.has_key?(:filter) && where_params.has_key?(:userid)
      whereQuery = filter_params[where_params[:filter]] + ' = ' + where_params[:userid]
    end
    # @movies = Movie.joins(:votes).where(whereQuery).ordered(sort_params[order_params[:order]])
    @movies = Movie.joins("LEFT JOIN `votes` ON votes.movie_id = movies.id").joins(:user)
                  .select("movies.*, sum(CASE WHEN votes.value = 1 THEN 1 ELSE 0 END) as likes, sum(CASE WHEN votes.value = 0 THEN 1 ELSE 0 END) as hates, users.name as user_name")
                  .where(whereQuery)
                  .group("movies.id")
                  .ordered(sort_params[order_params[:order]])
    @votes = Hash.new

    @movies.each do |movie|
      likesHash = Hash.new
      hatesHash = Hash.new
      votesArray = movie.votes

      votesArray.each do |vote|
        if vote.value == 1
          likesHash[vote.user_id] = 1
        else
          hatesHash[vote.user_id] = 0
        end
      end
      @votes[movie.title] = Hash['likes' => likesHash, 'hates' => hatesHash]
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      flash[:success] = 'Movie was successfully created'
      redirect_to @movie
    else
      render 'new'
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      flash[:success] = 'Movie was successfully updated'
      redirect_to @movie
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:success] = 'Movie was successfully Removed'
    redirect_to movies_path
  end

  def like
    # Get Movie model
    movie = Movie.find(params[:movieid])

    # User cannot vote for his movies
    if current_user.id != movie.user_id

      # Search for likes if exist unlike them
      like = Vote.find_by user: current_user, movie: movie, value: 1
      # Search for hates if exist delete them
      hate = Vote.find_by user: current_user, movie: movie, value: 0

      if like
        like.destroy
        flash[:success] = 'You Unlike the movie '+movie.title
      else
        like = Vote.new(user: current_user, movie: movie, value: 1)
        if like.save
          if hate
            hate.destroy
          end
          flash[:success] = 'You Like the movie '+movie.title
        else
          flash[:danger] = 'Failed to Like the movie'+movie.title
        end
      end
    end
    redirect_to movies_path
  end

  def hate
    # Get Movie model
    movie = Movie.find(params[:movieid])

    # User cannot vote for his movies
    if current_user.id != movie.user_id

      # Search for hates if exist unhate them
      hate = Vote.find_by user: current_user, movie: movie, value: 0
      # Search for likes if exist unlike them
      like = Vote.find_by user: current_user, movie: movie, value: 1

      if hate
        hate.destroy
        flash[:success] = 'You Unhate the movie '+movie.title
      else
        hate = Vote.new(user: current_user, movie: movie, value: 0)
        if hate.save
          if like
            like.destroy
          end
          flash[:success] = 'You Hate the movie '+movie.title
        else
          flash[:danger] = 'Failed to Hate the movie'+movie.title
        end
      end
    end
    redirect_to movies_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :description, :user).merge(user_id: current_user.id)
  end

  def order_params
    params.permit(:order);
  end

  def where_params
    params.permit(:filter, :userid);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MovieRama</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="blog-masthead">
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header"><%= link_to 'MovieRama', movies_path, class: 'navbar-brand' %></div>
        <% if user_signed_in? %>
            <ul class="nav navbar-nav pull-right">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <div class="navbar-right">
              <%= link_to 'Log In', new_user_session_path, class: 'btn btn-default navbar-btn btn-sm' %>
               Or
              <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary navbar-btn btn-xl' %>
            </div>
        <% end %>
      </div>
    </nav>
  </div>
</div>

<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-4"></div>
    <div class="col-xs-4">
      <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: "alert alert-#{name} text-center" %>
      <% end -%>
    </div>
    <div class="col-xs-4"></div>
  </div>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <%= yield %>
    </div>
    <div class="col-xs-1"></div>
  </div>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie, html:{class: 'form'}) do |f| %>



    <div class="form-group <%= (@movie.errors.include?(:title))? 'has-error':'' %>">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
      <% if @movie.errors.include?(:title) %>
          <% title_errors = @movie.errors[:title] %>
          <div class="alert alert-danger " style="margin-top: 5px;">
            <ul>
              <% if title_errors.kind_of?(Array) %>
                  <% title_errors.each do |error| %>
                      <li><%= error%></li>
                  <% end %>
              <% else %>
                  <% error = title_errors %>
                  <li><%= error%></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>

    <div class="form-group <%= (@movie.errors.include?(:description))? 'has-error':'' %>">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control', cols: '30', rows: '4' %>
    </div>

    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/movies/edit.html.erb
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
    <h1>Editing movie</h1>

    <%= render 'form' %>

    <%= link_to 'Back', movies_path, class: 'btn btn-default'  %>
  </div>
  <div class="col-xs-2"></div>
</div>

app/views/movies/index.html.erb
<div class="row">
  <div class="col-xs-11">
    Order:
    <%= link_to 'Likes', {controller: 'movies', order: 'by_likes'}, class: 'btn btn-success btn-sm' %>
    <%= link_to 'Hates ', {controller: 'movies', order: 'by_hates'}, class: 'btn btn-success btn-sm' %>
    <%= link_to 'Date', {controller: 'movies', order: 'by_date'}, class: 'btn btn-success btn-sm' %>
    <%= link_to 'Title', {controller: 'movies', order: 'by_title'}, class: 'btn btn-success btn-sm' %>
  </div>
  <% if user_signed_in? %>
      <div class="col-xs-1">
        <%= link_to 'New movie', new_movie_path, class: 'btn btn-success btn-sm pull-right' %>
      </div>
  <% end %>
</div>

<div class="row" style="margin-top: 10px">
  <div class="col-xs-12">
    <% @movies.each do |movie| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <h1><%= movie.title %></h1>
            <h6 class="small">Posted by
              <%= link_to controller: 'movies', filter: 'by_user', userid: movie.user_id do %>
                  <% if user_signed_in? && current_user.id == movie.user_id %>
                      You
                  <% else %>
                      <%= movie.user_name %>
                  <% end %>
              <% end %>
              <%= time_ago_in_words(movie.created_at) %> ago
              <% if user_signed_in? && current_user.id == movie.user_id %>
                  <%= link_to movie_path(movie), title: 'Show' do %><i class="glyphicon glyphicon-eye-open"></i>
                  <% end %>
                  <%= link_to edit_movie_path(movie), title: 'Edit' do %><i class="glyphicon glyphicon-pencil"></i>
                  <% end %>
                  <%= link_to movie_path(movie), title: 'Delete',
                              method: :delete,
                              data: {confirm: 'Are you sure?'} do %><i class="glyphicon glyphicon-trash"></i>
                  <% end %>
              <% end %>
            </h6>
            <p>
              <%= movie.description %>
            </p>
          </div>
          <div class="panel-footer">
            <%= (user_signed_in? && current_user.id != movie.user_id && movie.likes == 0 && movie.hates == 0) ? 'Be the first to vote for this movie: ' : '' %>
            <%= movie.likes %>
            <% if user_signed_in? && current_user.id != movie.user_id %>
                <%= link_to like_movie_path(movie), title: 'Like' do %>
                    <i class="glyphicon glyphicon-thumbs-up  <%= (@votes[movie.title]['likes'].has_key?(current_user.id)) ? 'text-primary' : 'text-muted' %>"></i>
                <% end %>
            <% else %>
                <i class="glyphicon glyphicon-thumbs-up"></i>
            <% end %>
            |
            <%= movie.hates %>
            <% if user_signed_in? && current_user.id != movie.user_id %>
                <%= link_to hate_movie_path(movie), title: 'Hate' do %>
                    <i id="thumbs-down" class="glyphicon glyphicon-thumbs-down <%= (@votes[movie.title]['hates'].has_key?(current_user.id)) ? 'text-primary' : 'text-muted' %>"></i>
                <% end %>
            <% else %>
                <i class="glyphicon glyphicon-thumbs-down"></i>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
    <h1>New Movie</h1>

    <%= render 'form' %>

    <%= link_to 'Back', movies_path, class: 'btn btn-default' %>
    </div>
  <div class="col-xs-2"></div>
</div>

app/views/movies/show.html.erb
<div class="jumbotron">
  <h1><%= @movie.title %></h1>
  <p><%= @movie.description %></p>
  <p><%= link_to 'Back', movies_path, class: 'btn btn-default btn-lg"'  %></p>
</div>